[devSQLDeployment]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = deploy
PASSWORD = deploy
VHOST = testHost
EXCHANGE = deployCluster
QUEUE = mysqlDeploy
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = mysqlDeploy

[qaSQLDeployment]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = deploy
PASSWORD = deploy
VHOST = testHost
EXCHANGE = deployCluster
QUEUE = mysqlDeploy
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = qa2deploy

[prodSQLDeployment]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = deploy
PASSWORD = deploy
VHOST = testHost
EXCHANGE = deployCluster
QUEUE = mysqlDeploy
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = prod2deploy

