[deployment]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = deploy
PASSWORD = deploy
VHOST = testHost
EXCHANGE = deployCluster
QUEUE = deployment
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = deployment

[devDeployment]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = deploy
PASSWORD = deploy
VHOST = testHost
EXCHANGE = devCluster
QUEUE = dev2deploy
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = dev2deploy

[qaDeployment]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = deploy
PASSWORD = deploy
VHOST = testHost
EXCHANGE = qaCluster
QUEUE = qa2deploy
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = qa2deploy

[prodDeployment]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = deploy
PASSWORD = deploy
VHOST = testHost
EXCHANGE = prodCluster
QUEUE = prod2deploy
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = prod2deploy

