[testServer]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[authenticationServer]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = loginSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[emailServer]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = web2sql
QUEUE = emailSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = emailSQL

[noBookAPI]
BROKER_HOST = 100.77.52.20
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2dmz
QUEUE = noBookAPI
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = noBookAPI

