[testServer]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[login]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql
QUEUE = loginSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = loginSQL

[books]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql     
QUEUE = bookSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = bookSQL

[reviews]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql
QUEUE = reviewSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = reviewSQL

[ratings]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql
QUEUE = ratingSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = ratingSQL

[groups]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql
QUEUE = groupSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = groupSQL

[watchlist]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql
QUEUE = watchlistSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = watchlistSQL


[booksB]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql     
QUEUE = bookSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = bookSQL

[reviewsB]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql
QUEUE = reviewSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = reviewSQL

[ratingsB]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql
QUEUE = ratingSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = ratingSQL

[groupsB]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql
QUEUE = groupSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = groupSQL

[watchlistB]
BROKER_HOST = 100.118.141.7
BROKER_PORT = 5672
USER = dbUser
PASSWORD = mySQL
VHOST = testHost
EXCHANGE = web2sql
QUEUE = watchlistSQL
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
ROUTING_KEY = watchlistSQL


